import { useEffect, useMemo, useState } from "react";
import {
  Search, Star, Moon, Sun, Copy, Check, Code2, Shield, Braces, Link,
  Hash, Clock, KeyRound, Regex, Palette, GitCompare, Binary, ArrowLeft,
  Sparkles, Menu, X, Database, Network, Type, Layers3, Home, SlidersHorizontal,
  Command, ChevronDown, CheckCircle2, AlertTriangle, RefreshCw, Download,
  LockKeyhole, FileJson, WandSparkles, Eye, Gauge
} from "lucide-react";

type Tool={id:string;name:string;description:string;category:string;icon:React.ReactNode};
const tools:Tool[]=[
 {id:"json",name:"JSON Formatter",description:"Format, validate and minify JSON locally.",category:"Data",icon:<Braces/>},
 {id:"base64",name:"Base64",description:"Encode and decode UTF-8 Base64 safely.",category:"Encoding",icon:<Binary/>},
 {id:"uuid",name:"UUID Generator",description:"Generate UUID v4 identifiers with Web Crypto.",category:"Generators",icon:<KeyRound/>},
 {id:"jwt",name:"JWT Decoder",description:"Inspect JWT header and payload without verification.",category:"Security",icon:<Shield/>},
 {id:"timestamp",name:"Timestamp",description:"Convert Unix timestamps and ISO dates.",category:"Date & Time",icon:<Clock/>},
 {id:"hash",name:"Hash Generator",description:"Generate SHA-256, SHA-384 and SHA-512 hashes.",category:"Security",icon:<Hash/>},
 {id:"regex",name:"Regex Tester",description:"Test patterns with match count and captures.",category:"Text",icon:<Regex/>},
 {id:"url",name:"URL Encoder",description:"Encode and decode complete URLs or components.",category:"Network",icon:<Link/>},
 {id:"color",name:"Color Converter",description:"HEX, RGB, HSL, HSV, CMYK and WCAG contrast.",category:"Design",icon:<Palette/>},
 {id:"diff",name:"Text Diff",description:"Compare two texts line by line with clear changes.",category:"Text",icon:<GitCompare/>},
 {id:"html",name:"HTML Escape",description:"Escape and unescape HTML entities locally.",category:"Text",icon:<Code2/>},
 {id:"cron",name:"Cron Helper",description:"Build and explain common cron expressions.",category:"Generators",icon:<Clock/>},
 {id:"password",name:"Password Generator",description:"Generate strong random passwords locally.",category:"Security",icon:<LockKeyhole/>},
 {id:"jsonpath",name:"JSON Preview",description:"Inspect JSON structure and keys quickly.",category:"Data",icon:<FileJson/>},
 {id:"text",name:"Text Utilities",description:"Count characters, words, lines and bytes.",category:"Text",icon:<Type/>},
 {id:"xml",name:"XML Formatter",description:"Format and validate XML documents locally.",category:"Data",icon:<Code2/>},
 {id:"csv",name:"CSV ↔ JSON",description:"Convert CSV data to JSON and JSON arrays to CSV.",category:"Data",icon:<Database/>},
 {id:"query",name:"Query String",description:"Parse and build URL query parameters.",category:"Network",icon:<Link/>},
 {id:"mime",name:"MIME Lookup",description:"Look up common MIME types and extensions.",category:"Network",icon:<Network/>},
 {id:"hmac",name:"HMAC Generator",description:"Generate HMAC SHA-256/384/512 signatures locally.",category:"Security",icon:<Shield/>},
 {id:"chmod",name:"Chmod Calculator",description:"Convert Unix permissions between octal and symbolic form.",category:"Generators",icon:<Code2/>},
 {id:"sql",name:"SQL Formatter",description:"Basic SQL formatting for common statements.",category:"Text",icon:<Braces/>},
 {id:"slug",name:"Slug Generator",description:"Turn text into clean URL-friendly slugs.",category:"Text",icon:<Link/>},
 {id:"case",name:"Case Converter",description:"Convert text to camel, snake, kebab and title case.",category:"Text",icon:<Type/>},
 {id:"lorem",name:"Lorem Generator",description:"Generate placeholder paragraphs locally.",category:"Generators",icon:<Sparkles/>},
 {id:"random",name:"Random Data",description:"Generate random hex, decimal and alphanumeric values.",category:"Generators",icon:<KeyRound/>},
 {id:"svg",name:"SVG Optimizer",description:"Apply safe basic cleanup to SVG source.",category:"Design",icon:<Code2/>},
 {id:"palette",name:"Palette Generator",description:"Create tints and shades from a base HEX color.",category:"Design",icon:<Palette/>},
 {id:"cidr",name:"IP / CIDR Calculator",description:"Inspect IPv4 network, broadcast and host range.",category:"Network",icon:<Network/>},
 {id:"env",name:".env Validator",description:"Check environment-file syntax without exposing values.",category:"Data",icon:<FileJson/>},
 {id:"json-ts",name:"JSON → TypeScript",description:"Generate TypeScript interfaces from JSON objects.",category:"Data",icon:<Braces/>},
 {id:"html-min",name:"HTML Minifier",description:"Basic HTML minification for quick local use.",category:"Text",icon:<Code2/>},
 {id:"css-min",name:"CSS Minifier",description:"Remove comments and unnecessary CSS whitespace.",category:"Text",icon:<Code2/>},
 {id:"markdown",name:"Markdown Preview",description:"Preview common Markdown safely without external requests.",category:"Text",icon:<Eye/>},
 {id:"http",name:"HTTP Status Lookup",description:"Quick reference for common HTTP status codes.",category:"Network",icon:<Network/>},
 {id:"base",name:"Number Base Converter",description:"Convert integers between binary, octal, decimal and hex.",category:"Encoding",icon:<Binary/>},
 {id:"strength",name:"Password Strength",description:"Estimate password entropy and common weaknesses.",category:"Security",icon:<Gauge/>},
 {id:"gradient",name:"CSS Gradient",description:"Build a linear gradient and copy the CSS.",category:"Design",icon:<Palette/>},
 {id:"urlparse",name:"URL Parser",description:"Inspect URL origin, path, query and fragment.",category:"Network",icon:<Link/>},
 {id:"uuidbulk",name:"Bulk UUID Generator",description:"Generate multiple UUID v4 identifiers at once.",category:"Generators",icon:<KeyRound/>},
 {id:"regexref",name:"Regex Cheat Sheet",description:"Handy reference for common regular-expression patterns.",category:"Text",icon:<Regex/>},
];
const categories=["All",...Array.from(new Set(tools.map(t=>t.category)))];
const icons:Record<string,React.ReactNode>={All:<Layers3 size={16}/>,Data:<Database size={16}/>,Encoding:<Binary size={16}/>,Security:<Shield size={16}/>,Text:<Type size={16}/>,Network:<Network size={16}/>,"Date & Time":<Clock size={16}/>,Design:<Palette size={16}/>,Generators:<KeyRound size={16}/>};
function storeGet(k:string,f:string){try{return localStorage.getItem(k)??f}catch{return f}}
function App(){
 const [query,setQuery]=useState(""); const [dark,setDark]=useState(()=>storeGet("devkit:theme","dark")!=="light");
 const [favorites,setFavorites]=useState<string[]>(()=>{try{const v=JSON.parse(storeGet("devkit:favorites","[]"));return Array.isArray(v)?v.filter((x:any)=>typeof x==="string"):[]}catch{return[]}});
 const [selected,setSelected]=useState<string|null>(null); const [category,setCategory]=useState("All"); const [favoriteOnly,setFavoriteOnly]=useState(false); const [mobileNav,setMobileNav]=useState(false); const [sort,setSort]=useState("name");
 useEffect(()=>{document.title=selected?`${tools.find(t=>t.id===selected)?.name??"Tool"} · DevKit`:"DevKit — Developer Toolbox"},[selected]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("global-search")?.focus()}if(e.key==="Escape")setMobileNav(false)};addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[]);
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();let a=tools.filter(t=>(category==="All"||t.category===category)&&(!favoriteOnly||favorites.includes(t.id))&&(!q||`${t.name} ${t.description} ${t.category}`.toLowerCase().includes(q)));return [...a].sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):a.category.localeCompare(b.category))},[query,category,favoriteOnly,favorites,sort]);
 const fav=(id:string)=>setFavorites(cur=>{const n=cur.includes(id)?cur.filter(x=>x!==id):[...cur,id];try{localStorage.setItem("devkit:favorites",JSON.stringify(n))}catch{}return n});
 const choose=(c:string)=>{setCategory(c);setFavoriteOnly(false);setQuery("");setMobileNav(false)};
 if(selected)return <ToolPage toolId={selected} onBack={()=>setSelected(null)} dark={dark} setDark={setDark}/>;
 return <div className={`app ${dark?"dark":"light"}`}>
  <header className="topbar"><div className="top-left"><button className="mobile-menu" onClick={()=>setMobileNav(true)}><Menu size={20}/></button><Brand/></div><label className="search global-search"><Search size={17}/><input id="global-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search for a tool..."/><kbd><Command size={11}/> K</kbd></label><div className="top-actions"><button className={`top-action favorites-action ${favoriteOnly?"selected":""}`} onClick={()=>{setCategory("All");setFavoriteOnly(v=>!v);setQuery("")}}><Star size={17} fill={favoriteOnly?"currentColor":"none"}/><span>Favorites</span><b>{favorites.length}</b></button><ThemeButton dark={dark} setDark={setDark}/><a className="github-button" href="https://github.com" target="_blank" rel="noreferrer">GitHub</a></div></header>
  <div className={`nav-overlay ${mobileNav?"show":""}`} onClick={()=>setMobileNav(false)}/><aside className={`sidebar ${mobileNav?"open":""}`}><div className="sidebar-mobile-head"><span>Navigation</span><button onClick={()=>setMobileNav(false)}><X size={18}/></button></div><button className={`home-link ${category==="All"&&!favoriteOnly?"active":""}`} onClick={()=>choose("All")}><Home size={17}/> Accueil</button><div className="nav-label">CATÉGORIES</div><nav className="category-nav">{categories.map(c=><button key={c} className={category===c&&!favoriteOnly?"category-link active":"category-link"} onClick={()=>choose(c)}>{icons[c]}<span>{c==="All"?"Tous les outils":c}</span>{c==="All"&&<b>{tools.length}</b>}</button>)}</nav><button className={`category-link favorites-nav ${favoriteOnly?"active":""}`} onClick={()=>{setFavoriteOnly(v=>!v);setCategory("All");setMobileNav(false)}}><Star size={16} fill={favoriteOnly?"currentColor":"none"}/><span>Favoris</span><b>{favorites.length}</b></button><div className="sidebar-card"><Sparkles size={18}/><strong>Open Source</strong><p>Local, rapide et gratuit. Propose une idée ou ajoute un outil.</p><a href="https://github.com" target="_blank" rel="noreferrer">Voir sur GitHub <ArrowLeft size={15}/></a></div><div className="sidebar-footer"><span>DevKit V1</span><span className="status"><i/> Local & prêt</span></div></aside>
  <main className="content"><section className="hero compact"><div className="eyebrow"><Sparkles size={13}/> OPEN SOURCE · FREE · LOCAL</div><h1>Les outils dev,<br/><span>bien pensés.</span></h1><p>Une toolbox moderne pour les tâches quotidiennes. Les données des outils locaux ne quittent pas ton navigateur.</p></section><div className="section-header"><div><h2>{favoriteOnly?"Favoris":category==="All"?"Tous les outils":category}</h2><span>{filtered.length} outil{filtered.length>1?"s":""}</span></div><button className="sort-button" onClick={()=>setSort(v=>v==="name"?"category":"name")}><SlidersHorizontal size={15}/> Trier par {sort==="name"?"nom":"catégorie"}<ChevronDown size={14}/></button></div><div className="filter-row">{categories.map(c=><button key={c} className={`filter-pill ${category===c&&!favoriteOnly?"selected":""}`} onClick={()=>choose(c)}>{c==="All"?"Tous":c}</button>)}</div><section className="tools-grid">{filtered.map((tool,i)=><article key={tool.id} className="tool-card" style={{"--delay":`${i*25}ms`} as React.CSSProperties} onClick={()=>setSelected(tool.id)}><div className="tool-card-top"><div className="tool-icon">{tool.icon}</div><button className={`favorite ${favorites.includes(tool.id)?"is-favorite":""}`} onClick={e=>{e.stopPropagation();fav(tool.id)}}><Star size={18} fill={favorites.includes(tool.id)?"currentColor":"none"}/></button></div><div className="tool-category">{tool.category}</div><h3>{tool.name}</h3><p>{tool.description}</p><div className="open-tool">Ouvrir <ArrowLeft size={14}/></div></article>)}</section></main>
 </div>;
}
function Brand(){return <div className="brand"><div className="logo"><Code2 size={21}/></div><div><strong>DevKit</strong><span>Developer Toolbox</span></div></div>}
function ThemeButton({dark,setDark}:{dark:boolean;setDark:(v:any)=>void}){return <button className="theme-button" onClick={()=>{const n=!dark;try{localStorage.setItem("devkit:theme",n?"dark":"light")}catch{}setDark(n)}}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button>}
function ToolPage({toolId,onBack,dark,setDark}:{toolId:string;onBack:()=>void;dark:boolean;setDark:(v:any)=>void}){const tool=tools.find(t=>t.id===toolId)!;return <div className={`app ${dark?"dark":"light"}`}><header className="topbar"><div className="top-left"><button className="back-top" onClick={onBack}><ArrowLeft size={17}/><span>Tools</span></button><Brand/></div><div className="top-actions"><ThemeButton dark={dark} setDark={setDark}/><a className="github-button" href="https://github.com" target="_blank" rel="noreferrer">GitHub</a></div></header><main className="tool-page"><button className="back-button" onClick={onBack}><ArrowLeft size={16}/> Back to tools</button><div className="tool-title"><div className="tool-icon large">{tool.icon}</div><div><div className="tool-category">{tool.category}</div><h1>{tool.name}</h1><p>{tool.description}</p></div></div>{toolId==="json"&&<JsonTool/>}{toolId==="base64"&&<Base64Tool/>}{toolId==="uuid"&&<UuidTool/>}{toolId==="jwt"&&<JwtTool/>}{toolId==="timestamp"&&<TimestampTool/>}{toolId==="hash"&&<HashTool/>}{toolId==="regex"&&<RegexTool/>}{toolId==="url"&&<UrlTool/>}{toolId==="color"&&<ColorTool/>}{toolId==="diff"&&<DiffTool/>}{toolId==="html"&&<HtmlTool/>}{toolId==="cron"&&<CronTool/>}{toolId==="password"&&<PasswordTool/>}{toolId==="jsonpath"&&<JsonPreview/>}{toolId==="text"&&<TextTool/>}{toolId==="xml"&&<XmlTool/>}{toolId==="csv"&&<CsvTool/>}{toolId==="query"&&<QueryTool/>}{toolId==="mime"&&<MimeTool/>}{toolId==="hmac"&&<HmacTool/>}{toolId==="chmod"&&<ChmodTool/>}{toolId==="sql"&&<SqlTool/>}{toolId==="slug"&&<SlugTool/>}{toolId==="case"&&<CaseTool/>}{toolId==="lorem"&&<LoremTool/>}{toolId==="random"&&<RandomTool/>}{toolId==="svg"&&<SvgTool/>}{toolId==="palette"&&<PaletteTool/>}{toolId==="cidr"&&<CidrTool/>}{toolId==="env"&&<EnvTool/>}{toolId==="json-ts"&&<JsonTsTool/>}{toolId==="html-min"&&<HtmlMinTool/>}{toolId==="css-min"&&<CssMinTool/>}{toolId==="markdown"&&<MarkdownTool/>}{toolId==="http"&&<HttpTool/>}{toolId==="base"&&<BaseConvertTool/>}{toolId==="strength"&&<StrengthTool/>}{toolId==="gradient"&&<GradientTool/>}{toolId==="urlparse"&&<UrlParseTool/>}{toolId==="uuidbulk"&&<UuidBulkTool/>}{toolId==="regexref"&&<RegexRefTool/>}</main></div>}
function Btn({children,kind="primary",onClick,disabled=false}:{children:React.ReactNode;kind?:"primary"|"secondary"|"ghost";onClick?:()=>void;disabled?:boolean}){return <button className={`btn btn-${kind}`} onClick={onClick} disabled={disabled}>{children}</button>}
function CopyBtn({value}:{value:string}){const[c,setC]=useState(false);return <Btn kind="secondary" onClick={async()=>{if(!value)return;try{await navigator.clipboard.writeText(value);setC(true);setTimeout(()=>setC(false),1200)}catch{}}}>{c?<><Check size={15}/> Copié !</>:<><Copy size={15}/> Copier</>}</Btn>}
function Workspace({input,setInput,output,error,children}:{input:string;setInput:(v:string)=>void;output:string;error?:string;children:React.ReactNode}){return <div className="workspace"><div className="workspace-grid"><div className="editor-panel"><div className="editor-label">ENTRÉE</div><textarea value={input} onChange={e=>setInput(e.target.value)} spellCheck={false} placeholder="Input..."/></div><div className="editor-panel output-wrapper"><div className="editor-label">RÉSULTAT</div><textarea value={output} readOnly spellCheck={false} placeholder="Output..."/><div className="output-copy"><CopyBtn value={output}/></div></div></div>{error&&<div className="error"><AlertTriangle size={15}/>{error}</div>}<div className="actions">{children}</div></div>}
function JsonTool(){const[i,setI]=useState("");const[o,setO]=useState("");const[e,setE]=useState("");const run=(min=false)=>{if(i.length>1000000){setE("Input too large (1 MB max).");return}try{setO(JSON.stringify(JSON.parse(i),null,min?0:2));setE("")}catch{setO("");setE("JSON invalide.")}};return <Workspace input={i} setInput={setI} output={o} error={e}><Btn onClick={()=>run()}><WandSparkles size={15}/> Formater</Btn><Btn kind="secondary" onClick={()=>run(true)}><Braces size={15}/> Minifier</Btn><Btn kind="ghost" onClick={()=>{setI("");setO("");setE("")}}>Effacer</Btn></Workspace>}
function Base64Tool(){const[i,setI]=useState("");const[o,setO]=useState("");const enc=()=>{try{const bytes=new TextEncoder().encode(i);let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));setO(btoa(bin))}catch{setO("Erreur d'encodage")}};const dec=()=>{try{const bin=atob(i.replace(/\s/g,""));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));setO(new TextDecoder().decode(bytes))}catch{setO("Base64 invalide")}};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={enc}><Binary size={15}/> Encoder</Btn><Btn kind="secondary" onClick={dec}>Décoder</Btn></Workspace>}
function UuidTool(){const[v,setV]=useState("");return <div className="single-tool"><div className="result big-result">{v||"Génère un UUID v4 sécurisé par Web Crypto."}</div><div className="actions"><Btn onClick={()=>setV(crypto.randomUUID())}><KeyRound size={15}/> Générer</Btn><CopyBtn value={v}/></div></div>}
function JwtTool(){const[i,setI]=useState("");const[o,setO]=useState("");const decode=()=>{try{const[a,b]=i.split(".");if(!a||!b)throw 0;const d=(s:string)=>{const base=s.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(s.length/4)*4,"=");const bin=atob(base);const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)};setO(JSON.stringify({header:JSON.parse(d(a)),payload:JSON.parse(d(b))},null,2))}catch{setO("JWT invalide ou mal formé.")}};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={decode}><Eye size={15}/> Décoder</Btn><div className="security-note"><Shield size={14}/> Décodage uniquement — signature non vérifiée.</div></Workspace>}
function TimestampTool(){const[i,setI]=useState(String(Math.floor(Date.now()/1000)));const num=/^-?\d+$/.test(i.trim())?Number(i):NaN;let date="";if(Number.isSafeInteger(num)){const d=new Date(Math.abs(num)<100000000000?num*1000:num);if(!Number.isNaN(d.getTime()))date=d.toISOString()} return <div className="single-tool"><input className="large-input" value={i} onChange={e=>setI(e.target.value)} placeholder="Unix timestamp"/><div className="result"><strong>{date||"Timestamp invalide"}</strong><span>Accepte secondes ou millisecondes.</span></div><CopyBtn value={date}/></div>}
function HashTool(){const[i,setI]=useState("");const[o,setO]=useState("");const hash=async(algo:"SHA-256"|"SHA-384"|"SHA-512")=>{const b=await crypto.subtle.digest(algo,new TextEncoder().encode(i));setO(Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join(""))};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={()=>hash("SHA-256")}><Hash size={15}/> SHA-256</Btn><Btn kind="secondary" onClick={()=>hash("SHA-384")}>SHA-384</Btn><Btn kind="secondary" onClick={()=>hash("SHA-512")}>SHA-512</Btn></Workspace>}
function RegexTool(){const[p,setP]=useState("");const[t,setT]=useState("");const[r,setR]=useState("");const test=()=>{try{if(p.length>5000)throw 0;const m=t.match(new RegExp(p,"g"));setR(m?`${m.length} correspondance(s)\n${m.join("\n")}`:"Aucune correspondance.")}catch{setR("Expression régulière invalide ou trop longue.")}};return <div className="single-tool"><input className="large-input" value={p} onChange={e=>setP(e.target.value)} placeholder="Expression régulière"/><textarea value={t} onChange={e=>setT(e.target.value)} placeholder="Texte à tester..."/><div className="actions"><Btn onClick={test}><Regex size={15}/> Tester</Btn></div><div className="result pre">{r}</div></div>}
function UrlTool(){const[i,setI]=useState("");const[o,setO]=useState("");return <Workspace input={i} setInput={setI} output={o}><Btn onClick={()=>setO(encodeURIComponent(i))}><Link size={15}/> Encoder</Btn><Btn kind="secondary" onClick={()=>{try{setO(decodeURIComponent(i))}catch{setO("Encodage URL invalide.")}}}>Décoder</Btn></Workspace>}
function ColorTool(){const[hex,setHex]=useState("#6366F1");const h=normalizeHex(hex);const rgb=hexToRgb(h);const hsl=rgb?hslFromRgb(rgb):null;const hsv=rgb?hsvFromRgb(rgb):null;const cmyk=rgb?cmykFromRgb(rgb):null;const whiteContrast=rgb?contrast(rgb,{r:255,g:255,b:255}):0;const blackContrast=rgb?contrast(rgb,{r:0,g:0,b:0}):0;const shades=rgb?Array.from({length:5},(_,n)=>mix(rgb,{r:0,g:0,b:0},n/5)):[];return <div className="color-tool"><div className="color-head"><input type="color" value={h || "#6366F1"} onChange={e=>setHex(e.target.value)} aria-label="Choose color"/><div><label>HEX</label><input className="large-input" value={hex} onChange={e=>setHex(e.target.value)} placeholder="#6366F1"/></div></div>{rgb?<><div className="color-preview" style={{background:h}}/><div className="color-values">{[['HEX',h],['RGB',`rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`],['HSL',`hsl(${hsl!.h}, ${hsl!.s}%, ${hsl!.l}%)`],['HSV',`hsv(${hsv!.h}, ${hsv!.s}%, ${hsv!.v}%)`],['CMYK',`cmyk(${cmyk!.c}%, ${cmyk!.m}%, ${cmyk!.y}%, ${cmyk!.k}%)`]].map(([a,v])=><div className="value-row" key={a}><b>{a}</b><code>{v}</code><CopyBtn value={String(v)}/></div>)}</div><div className="contrast-box"><strong>WCAG Contrast</strong><span>Sur blanc: {whiteContrast.toFixed(2)}:1 · {whiteContrast>=4.5?"AA texte normal":"Sous AA"}</span><span>Sur noir: {blackContrast.toFixed(2)}:1 · {blackContrast>=4.5?"AA texte normal":"Sous AA"}</span></div><div className="shade-row">{shades.map((c,i)=><button key={i} style={{background:rgbToHex(c)}} title={rgbToHex(c)} onClick={()=>setHex(rgbToHex(c))}/>)}</div></>:<div className="error"><AlertTriangle size={15}/> HEX invalide.</div>}</div>}
function DiffTool(){const[a,setA]=useState("");const[b,setB]=useState("");const aa=a.split("\n"),bb=b.split("\n");const n=Math.max(aa.length,bb.length);return <div className="single-tool"><div className="diff-grid"><textarea value={a} onChange={e=>setA(e.target.value)} placeholder="Original..."/><textarea value={b} onChange={e=>setB(e.target.value)} placeholder="Nouveau..."/></div><div className="diff-result">{Array.from({length:n},(_,i)=><div className={`diff-line ${aa[i]!==bb[i]?"changed":""}`} key={i}><span>{i+1}</span><code>{aa[i]??""}</code><b>→</b><code>{bb[i]??""}</code></div>)}</div></div>}
function HtmlTool(){const[i,setI]=useState("");const[o,setO]=useState("");return <Workspace input={i} setInput={setI} output={o}><Btn onClick={()=>setO(i.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;"))}><Code2 size={15}/> Échapper</Btn><Btn kind="secondary" onClick={()=>{const d=document.createElement("textarea");d.innerHTML=i;setO(d.value)}}>Déséchapper</Btn></Workspace>}
function CronTool(){const[parts,setParts]=useState(["*","*","*","*","*"]);const names=["Minute","Heure","Jour","Mois","Semaine"];const exp=parts.join(" ");const presets=["* * * * *","0 * * * *","0 0 * * *","0 9 * * 1-5","*/15 * * * *"];return <div className="single-tool"><div className="cron-grid">{parts.map((p,i)=><label key={i}>{names[i]}<input value={p} onChange={e=>setParts(x=>x.map((v,j)=>j===i?e.target.value:v))}/></label>)}</div><div className="result"><strong>{exp}</strong><span>{cronExplain(parts)}</span></div><div className="actions">{presets.map(p=><Btn key={p} kind="secondary" onClick={()=>setParts(p.split(" "))}>{p}</Btn>)}<CopyBtn value={exp}/></div></div>}
function PasswordTool(){const[len,setLen]=useState(24);const[p,setP]=useState("");const gen=()=>{const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=";const a=new Uint32Array(len);crypto.getRandomValues(a);setP(Array.from(a,x=>chars[x%chars.length]).join(""))};return <div className="single-tool"><label className="range-label">Longueur <b>{len}</b></label><input type="range" min="8" max="128" value={len} onChange={e=>setLen(+e.target.value)}/><div className="result big-result">{p||"Clique sur Générer pour créer un mot de passe."}</div><div className="actions"><Btn onClick={gen}><LockKeyhole size={15}/> Générer</Btn><CopyBtn value={p}/></div><div className="security-note"><Shield size={14}/> Généré localement avec Web Crypto.</div></div>}
function JsonPreview(){const[i,setI]=useState("");const[o,setO]=useState("");const run=()=>{try{const x=JSON.parse(i);const keys=Object.keys(x);setO(`Type: ${Array.isArray(x)?"array":typeof x}\nClés racine: ${keys.length}\n${keys.join("\n")}`)}catch{setO("JSON invalide.")}};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={run}><FileJson size={15}/> Inspecter</Btn></Workspace>}
function TextTool(){const[i,setI]=useState("");const bytes=new TextEncoder().encode(i).length;return <div className="stats-grid"><div><b>{i.length}</b><span>caractères</span></div><div><b>{i?i.trim().split(/\s+/).length:0}</b><span>mots</span></div><div><b>{i?i.split("\n").length:0}</b><span>lignes</span></div><div><b>{bytes}</b><span>octets UTF-8</span></div><textarea value={i} onChange={e=>setI(e.target.value)} placeholder="Écris ou colle ton texte..."/></div>}

function XmlTool(){const[i,setI]=useState("");const[o,setO]=useState("");const run=()=>{try{const doc=new DOMParser().parseFromString(i,"application/xml");if(doc.querySelector("parsererror"))throw 0;const raw=new XMLSerializer().serializeToString(doc);let level=0;const pretty=raw.replace(/>\s*</g,"><").replace(/</g,"\n<").trim().split("\n").map(line=>{if(/^<\//.test(line))level=Math.max(0,level-1);const out="  ".repeat(level)+line;if(/^<[^!?/][^>]*[^/]?>$/.test(line)&&!/<\/[^>]+>$/.test(line))level++;return out}).join("\n");setO(pretty)}catch{setO("XML invalide.")}};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={run}><Code2 size={15}/> Formater</Btn></Workspace>}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell="";if(row.some(x=>x!==""))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(x=>x!==""))rows.push(row);return rows}
function CsvTool(){const[i,setI]=useState("");const[o,setO]=useState("");const toJson=()=>{const r=parseCsv(i);if(r.length<1)return setO("CSV vide.");const h=r[0];setO(JSON.stringify(r.slice(1).map(x=>Object.fromEntries(h.map((k,j)=>[k,x[j]??""]))),null,2))};const toCsv=()=>{try{const a=JSON.parse(i);if(!Array.isArray(a)||!a.length||typeof a[0]!=="object")throw 0;const h=Array.from(new Set(a.flatMap((x:any)=>Object.keys(x))));const esc=(v:any)=>{const z=String(v??"");return /[",\n]/.test(z)?'"'+z.replace(/"/g,'""')+'"':z};setO([h.join(','),...a.map((x:any)=>h.map(k=>esc(x[k])).join(','))].join('\n'))}catch{setO("JSON attendu: tableau d'objets.")}};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={toJson}>CSV → JSON</Btn><Btn kind="secondary" onClick={toCsv}>JSON → CSV</Btn></Workspace>}
function QueryTool(){const[i,setI]=useState("name=DevKit&version=1");const[o,setO]=useState("");const parse=()=>{try{const q=i.includes('?')?i.slice(i.indexOf('?')+1).split('#')[0]:i;const p=new URLSearchParams(q);const obj:Record<string,string|string[]>={};p.forEach((v,k)=>{const cur=obj[k];obj[k]=cur===undefined?v:Array.isArray(cur)?[...cur,v]:[cur,v]});setO(JSON.stringify(obj,null,2))}catch{setO("Query string invalide.")}};const build=()=>{try{const x=JSON.parse(i);const p=new URLSearchParams();Object.entries(x).forEach(([k,v])=>Array.isArray(v)?v.forEach(y=>p.append(k,String(y))):p.set(k,String(v)));setO(p.toString())}catch{setO("Pour construire, colle un objet JSON.")}};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={parse}>Analyser</Btn><Btn kind="secondary" onClick={build}>Construire depuis JSON</Btn></Workspace>}
const mimeMap:Record<string,string>={json:"application/json",html:"text/html",css:"text/css",js:"text/javascript",ts:"text/plain",txt:"text/plain",csv:"text/csv",xml:"application/xml",svg:"image/svg+xml",png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg",gif:"image/gif",webp:"image/webp",pdf:"application/pdf",zip:"application/zip",wasm:"application/wasm",md:"text/markdown"};
function MimeTool(){const[i,setI]=useState("json");const q=i.trim().toLowerCase().replace(/^\./,'');const rev=Object.entries(mimeMap).filter(([k,v])=>k===q||v.includes(q));return <div className="single-tool"><input className="large-input" value={i} onChange={e=>setI(e.target.value)} placeholder="json, .svg, application/json..."/><div className="result pre">{rev.length?rev.map(([k,v])=>`.${k}  →  ${v}`).join('\n'):"Aucun type courant trouvé."}</div></div>}
function HmacTool(){const[i,setI]=useState("");const[key,setKey]=useState("");const[o,setO]=useState("");const run=async(algo:"SHA-256"|"SHA-384"|"SHA-512")=>{try{const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(key),{name:"HMAC",hash:algo},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(i));setO(Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,"0")).join(""))}catch{setO("HMAC indisponible dans ce contexte.")}};return <div className="single-tool"><input className="large-input" value={key} onChange={e=>setKey(e.target.value)} placeholder="Clé secrète locale"/><textarea value={i} onChange={e=>setI(e.target.value)} placeholder="Message..."/><div className="actions"><Btn onClick={()=>run("SHA-256")}>HMAC SHA-256</Btn><Btn kind="secondary" onClick={()=>run("SHA-512")}>SHA-512</Btn><CopyBtn value={o}/></div><div className="result pre">{o}</div></div>}
function ChmodTool(){const[i,setI]=useState("755");const valid=/^[0-7]{3,4}$/.test(i);const oct=valid?i.slice(-3):"";const tri=(n:number)=>`${n&4?'r':'-'}${n&2?'w':'-'}${n&1?'x':'-'}`;const sym=valid?oct.split('').map(x=>tri(+x)).join(''):"";return <div className="single-tool"><input className="large-input" value={i} onChange={e=>setI(e.target.value)} placeholder="755"/><div className="result"><strong>{valid?`${i} → ${sym}`:"Mode octal invalide"}</strong><span>Exemple: 644 = rw-r--r--, 755 = rwxr-xr-x</span></div></div>}
function SqlTool(){const[i,setI]=useState("");const[o,setO]=useState("");const run=()=>{const kw=["SELECT","FROM","WHERE","GROUP BY","ORDER BY","HAVING","LIMIT","JOIN","LEFT JOIN","RIGHT JOIN","INNER JOIN","OUTER JOIN","ON","UNION","VALUES","SET"];let x=i.replace(/\s+/g,' ').trim();kw.forEach(k=>x=x.replace(new RegExp(`\\s+${k.replace(' ','\\s+')}\\s+`,'ig'),`\n${k} `));x=x.replace(/\s*,\s*/g,',\n  ');setO(x)};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={run}>Formater SQL</Btn></Workspace>}
function SlugTool(){const[i,setI]=useState("");const slug=i.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');return <div className="single-tool"><textarea value={i} onChange={e=>setI(e.target.value)} placeholder="Mon super titre..."/><div className="result big-result">{slug}</div><CopyBtn value={slug}/></div>}
function CaseTool(){const[i,setI]=useState("");const words=i.trim().replace(/([a-z0-9])([A-Z])/g,'$1 $2').split(/[^A-Za-z0-9]+/).filter(Boolean);const lower=words.map(x=>x.toLowerCase());const vals=[['camelCase',lower.map((x,j)=>j?x[0]?.toUpperCase()+x.slice(1):x).join('')],['PascalCase',lower.map(x=>x[0]?.toUpperCase()+x.slice(1)).join('')],['snake_case',lower.join('_')],['kebab-case',lower.join('-')],['Title Case',lower.map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' ')]];return <div className="single-tool"><textarea value={i} onChange={e=>setI(e.target.value)} placeholder="Texte à convertir..."/><div className="color-values">{vals.map(([a,v])=><div className="value-row" key={a}><b>{a}</b><code>{v}</code><CopyBtn value={v}/></div>)}</div></div>}
const lorem="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";
function LoremTool(){const[n,setN]=useState(3);const out=Array.from({length:n},()=>lorem).join('\n\n');return <div className="single-tool"><label className="range-label">Paragraphes <b>{n}</b></label><input type="range" min="1" max="20" value={n} onChange={e=>setN(+e.target.value)}/><div className="result pre">{out}</div><CopyBtn value={out}/></div>}
function randomHex(n:number){const a=new Uint8Array(n);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('')}
function RandomTool(){const[n,setN]=useState(16);const[v,setV]=useState("");const gen=(kind:string)=>{if(kind==='hex')setV(randomHex(Math.ceil(n/2)).slice(0,n));else if(kind==='num'){const a=new Uint32Array(n);crypto.getRandomValues(a);setV(Array.from(a,x=>String(x%10)).join(''))}else{const c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';const a=new Uint32Array(n);crypto.getRandomValues(a);setV(Array.from(a,x=>c[x%c.length]).join(''))}};return <div className="single-tool"><label className="range-label">Longueur <b>{n}</b></label><input type="range" min="4" max="128" value={n} onChange={e=>setN(+e.target.value)}/><div className="actions"><Btn onClick={()=>gen('alpha')}>Alphanumérique</Btn><Btn kind="secondary" onClick={()=>gen('hex')}>Hex</Btn><Btn kind="secondary" onClick={()=>gen('num')}>Numérique</Btn></div><div className="result big-result">{v}</div><CopyBtn value={v}/></div>}
function SvgTool(){const[i,setI]=useState("");const[o,setO]=useState("");const run=()=>{let x=i.replace(/<!--([\s\S]*?)-->/g,'').replace(/>\s+</g,'><').replace(/\s{2,}/g,' ').trim();if(!/^<svg[\s>]/i.test(x))x='Entrée SVG invalide ou non reconnue.';setO(x)};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={run}>Optimiser (basique)</Btn></Workspace>}
function PaletteTool(){const[hex,setHex]=useState("#6366F1");const h=normalizeHex(hex),rgb=hexToRgb(h);const colors=rgb?[.8,.6,.4,.2,0].map(t=>rgbToHex(mix(rgb,{r:255,g:255,b:255},t))).concat([.2,.4,.6,.8].map(t=>rgbToHex(mix(rgb,{r:0,g:0,b:0},t)))):[];return <div className="single-tool"><input className="large-input" value={hex} onChange={e=>setHex(e.target.value)}/>{rgb?<div className="shade-row palette-wide">{colors.map(c=><button key={c} style={{background:c}} title={c} onClick={()=>setHex(c)}/>)}</div>:<div className="error">HEX invalide.</div>}<div className="result pre">{colors.join('\n')}</div></div>}
function ipNum(ip:string){const p=ip.split('.').map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return null;return (((p[0]<<24)>>>0)+(p[1]<<16)+(p[2]<<8)+p[3])>>>0} function numIp(n:number){return [24,16,8,0].map(s=>(n>>>s)&255).join('.')}
function CidrTool(){const[i,setI]=useState("192.168.1.10/24");let out="";try{const[ip,c]=i.trim().split('/');const n=ipNum(ip),bits=Number(c);if(n===null||!Number.isInteger(bits)||bits<0||bits>32)throw 0;const mask=bits===0?0:(0xffffffff<<(32-bits))>>>0;const net=(n&mask)>>>0,bcast=(net|(~mask>>>0))>>>0;const hosts=bits>=31?0:Math.max(0,2**(32-bits)-2);out=`Network: ${numIp(net)}/${bits}\nBroadcast: ${numIp(bcast)}\nFirst host: ${bits>=31?'N/A':numIp(net+1)}\nLast host: ${bits>=31?'N/A':numIp(bcast-1)}\nUsable hosts: ${hosts.toLocaleString()}`}catch{out="IPv4/CIDR invalide."}return <div className="single-tool"><input className="large-input" value={i} onChange={e=>setI(e.target.value)}/><div className="result pre">{out}</div></div>}
function EnvTool(){const[i,setI]=useState("");const lines=i.split(/\r?\n/);const issues:string[]=[];lines.forEach((line,idx)=>{const x=line.trim();if(!x||x.startsWith('#'))return;if(!/^[A-Za-z_][A-Za-z0-9_]*\s*=/.test(x))issues.push(`Ligne ${idx+1}: syntaxe KEY=VALUE invalide`)});const keys=lines.map(x=>x.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/)?.[1]).filter(Boolean) as string[];const dup=[...new Set(keys.filter((x,j)=>keys.indexOf(x)!==j))];dup.forEach(x=>issues.push(`Clé dupliquée: ${x}`));return <div className="single-tool"><textarea value={i} onChange={e=>setI(e.target.value)} placeholder={'API_URL=https://example.com\nFEATURE_FLAG=true'}/><div className="result pre">{issues.length?issues.join('\n'):`${keys.length} variable(s) détectée(s). Aucune erreur de syntaxe.`}</div><div className="security-note"><Shield size={14}/> Validation 100% locale; aucune valeur n'est envoyée.</div></div>}
function tsType(v:any,name:string,defs:string[]):string{if(v===null)return 'null';if(Array.isArray(v))return v.length?`${tsType(v[0],name+'Item',defs)}[]`:'unknown[]';if(typeof v==='object'){const t=name.replace(/[^A-Za-z0-9_]/g,'')||'Generated';defs.push(`export interface ${t} {\n${Object.entries(v).map(([k,x])=>`  ${/^[A-Za-z_$][\w$]*$/.test(k)?k:JSON.stringify(k)}: ${tsType(x,t+k[0]?.toUpperCase()+k.slice(1),defs)};`).join('\n')}\n}`);return t}return typeof v==='number'?'number':typeof v==='boolean'?'boolean':typeof v==='string'?'string':'unknown'}
function JsonTsTool(){const[i,setI]=useState("");const[o,setO]=useState("");const run=()=>{try{const x=JSON.parse(i),defs:string[]=[];const root=tsType(x,'Root',defs);setO(defs.reverse().join('\n\n')+(defs.length?'':'export type Root = '+root+';'))}catch{setO("JSON invalide.")}};return <Workspace input={i} setInput={setI} output={o}><Btn onClick={run}>Générer TypeScript</Btn></Workspace>}
function HtmlMinTool(){const[i,setI]=useState("");const[o,setO]=useState("");return <Workspace input={i} setInput={setI} output={o}><Btn onClick={()=>setO(i.replace(/<!--([\s\S]*?)-->/g,'').replace(/>\s+</g,'><').replace(/\s{2,}/g,' ').trim())}>Minifier HTML</Btn></Workspace>}
function CssMinTool(){const[i,setI]=useState("");const[o,setO]=useState("");return <Workspace input={i} setInput={setI} output={o}><Btn onClick={()=>setO(i.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\s*([{}:;,>])\s*/g,'$1').replace(/;}/g,'}').replace(/\s+/g,' ').trim())}>Minifier CSS</Btn></Workspace>}
function mdSafe(s:string){const e=s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return e.split('\n').map(line=>{if(/^### /.test(line))return `<h3>${line.slice(4)}</h3>`;if(/^## /.test(line))return `<h2>${line.slice(3)}</h2>`;if(/^# /.test(line))return `<h1>${line.slice(2)}</h1>`;if(/^[-*] /.test(line))return `<li>${line.slice(2)}</li>`;return `<p>${line.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`(.+?)`/g,'<code>$1</code>')}</p>`}).join('')}
function MarkdownTool(){const[i,setI]=useState("# DevKit\n\n**Markdown** preview with `safe` HTML.");return <div className="single-tool"><textarea value={i} onChange={e=>setI(e.target.value)}/><div className="result markdown-preview" dangerouslySetInnerHTML={{__html:mdSafe(i)}}/></div>}
const httpStatuses:Record<number,string>={100:'Continue',200:'OK',201:'Created',202:'Accepted',204:'No Content',301:'Moved Permanently',302:'Found',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',405:'Method Not Allowed',408:'Request Timeout',409:'Conflict',410:'Gone',413:'Content Too Large',415:'Unsupported Media Type',418:"I'm a teapot",422:'Unprocessable Content',429:'Too Many Requests',500:'Internal Server Error',501:'Not Implemented',502:'Bad Gateway',503:'Service Unavailable',504:'Gateway Timeout'};
function HttpTool(){const[i,setI]=useState("404");const q=i.trim().toLowerCase();const rows=Object.entries(httpStatuses).filter(([c,n])=>c.includes(q)||n.toLowerCase().includes(q));return <div className="single-tool"><input className="large-input" value={i} onChange={e=>setI(e.target.value)} placeholder="404 ou Not Found"/><div className="result pre">{rows.length?rows.map(([c,n])=>`${c} — ${n}`).join('\n'):"Aucun statut courant trouvé."}</div></div>}
function BaseConvertTool(){const[i,setI]=useState("255");const[from,setFrom]=useState(10);const clean=i.trim().toLowerCase();const valid=from===2?/^[01]+$/.test(clean):from===8?/^[0-7]+$/.test(clean):from===10?/^[0-9]+$/.test(clean):/^[0-9a-f]+$/.test(clean);const n=valid?parseInt(clean,from):NaN;return <div className="single-tool"><div className="actions"><input className="large-input" value={i} onChange={e=>setI(e.target.value)}/><select className="large-input inline-select" value={from} onChange={e=>setFrom(+e.target.value)}><option value={2}>Binary</option><option value={8}>Octal</option><option value={10}>Decimal</option><option value={16}>Hex</option></select></div><div className="result pre">{Number.isFinite(n)?`BIN: ${n.toString(2)}\nOCT: ${n.toString(8)}\nDEC: ${n.toString(10)}\nHEX: ${n.toString(16).toUpperCase()}`:"Valeur invalide pour cette base."}</div></div>}
function StrengthTool(){const[i,setI]=useState("");const pool=(/[a-z]/.test(i)?26:0)+(/[A-Z]/.test(i)?26:0)+(/\d/.test(i)?10:0)+(/[^A-Za-z0-9]/.test(i)?32:0);const bits=i.length&&pool?Math.round(i.length*Math.log2(pool)):0;const score=Math.min(4,(i.length>=8?1:0)+(i.length>=12?1:0)+(/[A-Z]/.test(i)&&/[a-z]/.test(i)&&/\d/.test(i)?1:0)+(/[^A-Za-z0-9]/.test(i)?1:0));const names=['Très faible','Faible','Correct','Fort','Très fort'];return <div className="single-tool"><input className="large-input" type="password" value={i} onChange={e=>setI(e.target.value)} placeholder="Mot de passe à analyser"/><div className="result"><strong>{names[score]}</strong><span>Entropie théorique approximative: {bits} bits</span><span>{i.length<12?'Conseil: vise au moins 12–16 caractères.':'Bonne longueur.'}</span></div><div className="security-note"><Shield size={14}/> Estimation locale, pas un audit cryptographique.</div></div>}
function GradientTool(){const[a,setA]=useState('#6366F1');const[b,setB]=useState('#22C55E');const[deg,setDeg]=useState(135);const css=`linear-gradient(${deg}deg, ${a}, ${b})`;return <div className="single-tool"><div className="actions"><input type="color" value={a} onChange={e=>setA(e.target.value)}/><input type="color" value={b} onChange={e=>setB(e.target.value)}/></div><label className="range-label">Angle <b>{deg}°</b></label><input type="range" min="0" max="360" value={deg} onChange={e=>setDeg(+e.target.value)}/><div className="gradient-preview" style={{background:css}}/><div className="result pre">background: {css};</div><CopyBtn value={`background: ${css};`}/></div>}
function UrlParseTool(){const[i,setI]=useState("https://example.com/path?foo=bar#section");let out="";try{const u=new URL(i);out=`Protocol: ${u.protocol}\nOrigin: ${u.origin}\nHost: ${u.host}\nHostname: ${u.hostname}\nPort: ${u.port||'(default)'}\nPath: ${u.pathname}\nQuery: ${u.search||'(none)'}\nHash: ${u.hash||'(none)'}`}catch{out="URL absolue invalide."}return <div className="single-tool"><input className="large-input" value={i} onChange={e=>setI(e.target.value)}/><div className="result pre">{out}</div></div>}
function safeUuid(){if(crypto.randomUUID)return crypto.randomUUID();const b=new Uint8Array(16);crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
function UuidBulkTool(){const[n,setN]=useState(10);const[o,setO]=useState("");return <div className="single-tool"><label className="range-label">Quantité <b>{n}</b></label><input type="range" min="1" max="100" value={n} onChange={e=>setN(+e.target.value)}/><div className="actions"><Btn onClick={()=>setO(Array.from({length:n},safeUuid).join('\n'))}>Générer</Btn><CopyBtn value={o}/></div><div className="result pre">{o}</div></div>}
function RegexRefTool(){const rows=[['Any character','.', 'Matches any character except newline'],['Digit','\\d','0–9'],['Word','\\w','Letters, digits, underscore'],['Whitespace','\\s','Space, tab, newline'],['Start / End','^  $','Anchors'],['Zero or more','*','Quantifier'],['One or more','+','Quantifier'],['Optional','?','Zero or one'],['Group','(abc)','Capturing group'],['Non-capturing','(?:abc)','Group without capture'],['Choice','a|b','Alternation'],['Character set','[a-z]','Range or set'],['Negative set','[^0-9]','Anything except set']];return <div className="single-tool"><div className="color-values">{rows.map(([a,b,c])=><div className="value-row" key={a}><b>{a}</b><code>{b}</code><span>{c}</span></div>)}</div></div>}

function normalizeHex(x:string){let s=x.trim().replace(/^#/,'');if(/^[0-9a-fA-F]{3}$/.test(s))s=s.split('').map(c=>c+c).join('');return /^[0-9a-fA-F]{6}$/.test(s)?`#${s.toUpperCase()}`:""}
type RGB={r:number;g:number;b:number}; function hexToRgb(h:string):RGB|null{if(!h)return null;return{r:parseInt(h.slice(1,3),16),g:parseInt(h.slice(3,5),16),b:parseInt(h.slice(5,7),16)}}
function hslFromRgb({r,g,b}:RGB){let R=r/255,G=g/255,B=b/255,max=Math.max(R,G,B),min=Math.min(R,G,B),h=0,s=0,l=(max+min)/2;if(max!==min){let d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case R:h=(G-B)/d+(G<B?6:0);break;case G:h=(B-R)/d+2;break;default:h=(R-G)/d+4}h*=60}return{h:Math.round(h),s:Math.round(s*100),l:Math.round(l*100)}}
function hsvFromRgb({r,g,b}:RGB){let R=r/255,G=g/255,B=b/255,max=Math.max(R,G,B),min=Math.min(R,G,B),d=max-min,h=0;if(d){if(max===R)h=60*((G-B)/d%6);else if(max===G)h=60*((B-R)/d+2);else h=60*((R-G)/d+4);if(h<0)h+=360}return{h:Math.round(h),s:Math.round((max?d/max:0)*100),v:Math.round(max*100)}}
function cmykFromRgb({r,g,b}:RGB){let R=r/255,G=g/255,B=b/255,k=1-Math.max(R,G,B);if(k===1)return{c:0,m:0,y:0,k:100};return{c:Math.round((1-R-k)/(1-k)*100),m:Math.round((1-G-k)/(1-k)*100),y:Math.round((1-B-k)/(1-k)*100),k:Math.round(k*100)}}
function lum(c:RGB){const f=(v:number)=>{v/=255;return v<=.03928?v/12.92:((v+.055)/1.055)**2.4};return .2126*f(c.r)+.7152*f(c.g)+.0722*f(c.b)} function contrast(a:RGB,b:RGB){const A=lum(a),B=lum(b);return(Math.max(A,B)+.05)/(Math.min(A,B)+.05)} function mix(a:RGB,b:RGB,t:number):RGB{return{r:Math.round(a.r+(b.r-a.r)*t),g:Math.round(a.g+(b.g-a.g)*t),b:Math.round(a.b+(b.b-a.b)*t)}} function rgbToHex(c:RGB){return`#${[c.r,c.g,c.b].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase()}`}
function cronExplain(p:string[]){return p.join(" ")==="* * * * *"?"Toutes les minutes.":p[0]==="0"&&p[1]==="0"?"À minuit selon les autres champs.":"Expression personnalisée — vérifie-la avant de la déployer."}
export default App;
